<?xml version="1.0" encoding="UTF-8"?><testrun name="CalculatorProjectTest" project="JUnitProjectTest" tests="7" started="7" failures="2" errors="0" ignored="0">
  <testsuite name="io.cal.CalculatorProjectTest" time="0.087" displayname="CalculatorProjectTest" uniqueid="[engine:junit-jupiter]/[class:io.cal.CalculatorProjectTest]">
    <testcase name="areaofcircle" classname="io.cal.CalculatorProjectTest" time="0.04" displayname="areaofcircle()" uniqueid="[engine:junit-jupiter]/[class:io.cal.CalculatorProjectTest]/[method:areaofcircle()]"/>
    <testcase name="positivenumber" classname="io.cal.CalculatorProjectTest" time="0.001" displayname="positivenumber()" uniqueid="[engine:junit-jupiter]/[class:io.cal.CalculatorProjectTest]/[method:positivenumber()]"/>
    <testcase name="add" classname="io.cal.CalculatorProjectTest" time="0.001" displayname="add()" uniqueid="[engine:junit-jupiter]/[class:io.cal.CalculatorProjectTest]/[method:add()]"/>
    <testcase name="div" classname="io.cal.CalculatorProjectTest" time="0.02" displayname="div()" uniqueid="[engine:junit-jupiter]/[class:io.cal.CalculatorProjectTest]/[method:div()]">
      <failure>
        <expected>2</expected>
        <actual>18</actual>
        org.opentest4j.AssertionFailedError: Divide Function can Calulate Two Integers..! ==&gt; expected: &lt;2&gt; but was: &lt;18&gt;&#13;
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)&#13;
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)&#13;
	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)&#13;
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)&#13;
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:563)&#13;
	at io.cal.CalculatorProjectTest.div(CalculatorProjectTest.java:46)&#13;
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)&#13;
&#13;

      </failure>
    </testcase>
    <testcase name="mul" classname="io.cal.CalculatorProjectTest" time="0.001" displayname="mul()" uniqueid="[engine:junit-jupiter]/[class:io.cal.CalculatorProjectTest]/[method:mul()]"/>
    <testcase name="sub" classname="io.cal.CalculatorProjectTest" time="0.001" displayname="sub()" uniqueid="[engine:junit-jupiter]/[class:io.cal.CalculatorProjectTest]/[method:sub()]"/>
    <testcase name="divtest" classname="io.cal.CalculatorProjectTest" time="0.017" displayname="divtest()" uniqueid="[engine:junit-jupiter]/[class:io.cal.CalculatorProjectTest]/[method:divtest()]">
      <failure>org.opentest4j.AssertionFailedError: div Function can calculate two integers  ==&gt; Expected java.lang.NullPointerException to be thrown, but nothing was thrown.&#13;
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:152)&#13;
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:73)&#13;
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:39)&#13;
	at org.junit.jupiter.api.Assertions.assertThrows(Assertions.java:3131)&#13;
	at io.cal.CalculatorProjectTest.divtest(CalculatorProjectTest.java:84)&#13;
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)&#13;
&#13;
</failure>
    </testcase>
  </testsuite>
</testrun>
